/**
 * Docker Compose template for the claude-code-proxy container.
 *
 * Generates a security-hardened docker-compose YAML file that routes
 * Claude Code CLI requests through the cloud.ru FM proxy.
 *
 * Security hardening (E-01, QCSD-05):
 *   - Pinned image version (R013)
 *   - Localhost-only port binding (R008, S-01)
 *   - no-new-privileges, cap_drop ALL, read_only
 *   - Resource limits (512 MB, 1 CPU)
 *   - Non-root user (1000:1000)
 *
 * Health check (MQ-24, MQ-26):
 *   - 10 s interval, 5 s timeout, 3 retries, 10 s start_period
 */

import {
  CLOUDRU_BASE_URL,
  CLOUDRU_PROXY_IMAGE,
  CLOUDRU_PROXY_PORT_DEFAULT,
  type CloudruModelPreset,
} from "../config/cloudru-fm.constants.js";

export interface ProxyComposeParams {
  /** Host port to bind (default: CLOUDRU_PROXY_PORT_DEFAULT). */
  port?: number;
  /** Model preset determining BIG/MIDDLE/SMALL env vars. */
  preset: CloudruModelPreset;
}

/**
 * Returns a docker-compose YAML string for the claude-code-proxy.
 *
 * The CLOUDRU_API_KEY is read from the .env file placed next to the
 * compose file -- it is never embedded in the YAML itself (I-01).
 *
 * Usage:
 *   docker compose -f docker-compose.cloudru-proxy.yml up -d
 */
export function generateProxyDockerCompose(params: ProxyComposeParams): string {
  const port = params.port ?? CLOUDRU_PROXY_PORT_DEFAULT;
  const { preset } = params;

  return `# Auto-generated by OpenClaw wizard -- do not edit manually.
# Run: docker compose -f docker-compose.cloudru-proxy.yml up -d

services:
  claude-code-proxy:
    image: ${CLOUDRU_PROXY_IMAGE}
    container_name: claude-code-proxy
    restart: unless-stopped
    ports:
      # Localhost-only binding (S-01, R008).
      - "127.0.0.1:${port}:8082"
    environment:
      # HOST must be 0.0.0.0 inside the container for Docker port
      # forwarding to work (WARNING-003).  The host-side binding
      # above restricts external access to localhost.
      HOST: "0.0.0.0"
      PORT: "8082"
      API_BASE_URL: "${CLOUDRU_BASE_URL}"
      API_KEY: "\${CLOUDRU_API_KEY}"
      BIG_MODEL: "${preset.big}"
      MIDDLE_MODEL: "${preset.middle}"
      SMALL_MODEL: "${preset.small}"
      # Disable extended thinking to avoid GLM-4.7 instability (ADR-005).
      DISABLE_THINKING: "true"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    user: "1000:1000"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
`;
}

/** Suggested docker-compose filename. */
export const CLOUDRU_COMPOSE_FILENAME = "docker-compose.cloudru-proxy.yml";
